      n         $ Do you want a tutorial session and tutorial output?
   74.37600     $ Panel length in the plane of the screen, L2
         0      $ Enter control (0 or 1) for stringers at panel edges
         2      $ Enter control (1=sym; 2=s.s.) for boundary condition
         0      $ Enter ILOCAL=0 for panel buckling; 1 for local buckling, ILOCAL
         1      $ Number of halfwaves in the axial direction [see H(elp)],NWAVE
         1      $ How many eigenvalues (get at least 3) do you want?
