      SUBROUTINE GETCOM(IFILE)
C
C  PURPOSE IS TO RETRIEVE LABELLED COMMON BLOCKS
C
      CHARACTER*80 WORDP,WORDV,WORDA,WORDC,WORDD,WORDL,WORDE,WORDIQ
      CHARACTER*80 WRDMAT

      CHARACTER*12 MARLEG,OBJLEG
      CHARACTER*16 VARLEG

      CHARACTER*80 PCWRD1,PCWRD2

      REAL NXVAR0,NYVAR0,NXYVR0
      REAL MSLOPE
C
      COMMON/GEOM1/AXIAL,CIRC,R
      COMMON/GEOM0/B0(2),B20(2),H0(2),W0(2),W20(2)
      COMMON/GEOM2/B(2),B2(2),H(2),W(2),W2(2)
      COMMON/GEOM3/ISTIF(2),NLAYER(4,2),NSEG(2),INTEXT(2)
      COMMON/GEOM0S/B0SUB(2),B20SUB(2),H0SUB(2),W0SUB(2),W20SUB(2)
      COMMON/GEOM2S/BSUBX(2),B2SUBX(2),HSUBX(2),WSUBX(2),W2SUBX(2)
      COMMON/GEOM3S/ISTFSB(2),NLAYSB(4,2),NSEGSB(2),INTXSB(2)
      COMMON/GEOM4S/IMTSUB(8)
      COMMON/GEOM4/IWIND(8)
      COMMON/GEOM5/RAD2,CURV2
      COMMON/GEOM6/IFAY(2),ITRTOT,IMISCL(27)
      COMMON/PLTVAR/IPV(50),ICV(99),NPLT,NMARGN,ITER1,NTIT(5,2)
      COMMON/WORDS3/WORDIQ(20)
      COMMON/PARAM3/CINEQ(200),DPWREQ(10,20)
      COMMON/PARAM4/IDINEQ(200),NINEQ,JINEQ(20),IEQTYP(20)
      COMMON/ISKIPY/ISKIPX(910)
      COMMON/TMATL1/MAXMAT(1),IPMATL(10)
      COMMON/TMATL2/PARMAT(200),TEMPJ(10,20,10),FTEMPJ(10,20,10)
      COMMON/TMATL3/WRDMAT(200)
      COMMON/PRESUR/P
      COMMON/LAYER/MATL(90),LTYPE(99,5,2),T(90),ANGLE(90)
      COMMON/MATER1/E1(20),E2(20),G(20),FNU(20),DENS(20)
      COMMON/MATRAN/G13(20),G23(20)
      COMMON/MATRN2/GTX(10),GTY(10),GTS(2),TEFF(2)
      COMMON/THICK/TX(5),TY(5)
      COMMON/MATER2/STRAIN(400),STRESS(400)
      COMMON/MATER3/STSMAX(10),STNMAX(5,10)
      COMMON/MATERT/ALPHA1(20),ALPHA2(20),CURETP(20),ICOCUR(2)
      COMMON/MATER4/TAPE(20),TMINUM(20),FAILSC(100)
      COMMON/MATER5/DEGRAD(500)
      COMMON/MATER6/SIGLUE(20)
      COMMON/MATER7/ISOMAT(20),ISOEFF(20)
      COMMON/LWRUPR/VLB(50),VUB(50),CLINK(50,5),VLINK(50),VBV(99)
      COMMON/ADDRSS/IADDV(50),IADDP(99),IADDA(50),IADDC(99),IADDD(50)
      COMMON/NUMPAR/NPAR,NVARB,NALLOW,NCONST,NDEC,NLINK,NESCAP,ITYPE
      COMMON/PARAMS/PAR(99),VAR(50),ALLOW(50),CONST(99),DEC(50),ESC(50)
      COMMON/WORDS/WORDP(99),WORDV(50),WORDA(50),WORDC(99),WORDD(50)
      COMMON/WORDS2/WORDL(50),WORDE(50)
      COMMON/OPTVAR/IDV(50),ILV(50),IDLINK(50,5),IEV(50),JTERMS(50)
      COMMON/PARAM2/CPWR(250),CLINK0(50)
      COMMON/ROTALW/CHIALW,PHIMAX
      COMMON/ALLCIJ/CX(180),CY(180),CS(36)
      COMMON/LOADS/FNX(1),FNY,FNXY,RESULT(3,5,2)
      COMMON/LOADS2/FNX0(1),FNY0,FNXY0,RESFIX(3,5,2)
      COMMON/GNNSTB/EIGGEN(1),EIGLOC,FNLOC,EIGSTF,FNSTF
      COMMON/NVARXX/FNVAR(554)
      COMMON/BOSEGS/NSEGB5,IPOINT(295)
      COMMON/BOSEG2/NSEGB3,IPOIN3(295)
      COMMON/TOTPTG/M3G
      COMMON/DSPACG/IDSG
      COMMON/SEGSG/NSEGG(1),M2G,I5G(95),I2GG,I2GGG   
      COMMON/BLKG/IBLKG(1),NGBKG(20),NKFG(20)    
      COMMON/BCKG/IDRWG(100)   
      COMMON/LOCATG/ILOCPG(1),ILOCBG,IRWCPG(98),IRWCBG(98),IIWPG,IIWBG 
      COMMON/NCONDG/NCONDG     
      COMMON/RING3G/D1G(98),D2G(98)    
      COMMON/JUNCTG/IFIXBG(588),IFXBG(588),ITYPEG(98) 
      COMMON/BKSIZG/IMAXPG(1),IMAXBG,KMAXPG(20),KMAXBG(20)   
      COMMON/ILOCGG/ILOCG(600),IWG(210),DSG(200)
      COMMON/IDHIGG/IDMAXG
      COMMON/GENPRE/FBPRE(1),PRELEN,FMISC(28)
      COMMON/SEGSLP/MSLOPE(8)
      COMMON/WORDSX/VARLEG(50),MARLEG(99),OBJLEG
      COMMON/GEOMN3/IBVAR,VARPLT(30)
      COMMON/GEOMN4/ICURV,FNXPLT(93)
      COMMON/FSAFEB/FSAFEP(99)
      COMMON/FSAFB2/FSAFP2(99)
      COMMON/FSAFWD/PCWRD1(99),PCWRD2(99)
      COMMON/CPLT12/CPLOT1,CPLOT2
      COMMON/LINCIJ/CX0(180),NXVAR0(184),NYVAR0(184),NXYVR0(184)
      COMMON/NCASEP/NCASEX(5)
      COMMON/ISOGR/ISOGRD,ISOANG
      COMMON/XFOUND/EFOUND(18)
      COMMON/XSANDW/ISANDW(16)
      COMMON/PSANDW/FACSKN(4)
      COMMON/XFOUN1/WOVERL(340)
      COMMON/XFOUN2/ECCORE(24)
      COMMON/XFOUN3/THEX(100)
      COMMON/XFOUN4/ECOREX(60)
      COMMON/XFOUN5/KCORE(36)
      COMMON/XFOUN7/WGTTAB(720)
      COMMON/XFOUN8/SHWTAB(720)
      COMMON/XFOUN9/KOUNTP(60)
      COMMON/MATER8/BNDOVR(50)
      COMMON/MATER9/ICAND(20)
      COMMON/PARAM6/CCROSS(200)
      COMMON/PARAM7/IDINQ1(420)
      COMMON/IZSTIX/IZSTIF(2)
      COMMON/BOSGS2/NSGB52(1),IPINT2(295)
      COMMON/TOTPTR/M3R
      COMMON/DSPACR/IDSR
      COMMON/SEGSR/NSEGR(1),M2R,I5R(95),I2GR,I2GGR   
      COMMON/BLKR/IBLKR(1),NGBKR(20),NKFR(20)    
      COMMON/BCKR/IDRWR(100)   
      COMMON/LOCATR/ILOCPR(1),ILOCBR,IRWCPR(98),IRWCBR(98),IIWPR,IIWBR 
      COMMON/NCONDX/NCONDR
      COMMON/RING3R/D1R(98),D2R(98)    
      COMMON/JUNCTR/IFIXBR(588),IFXBR(588),ITYPER(98) 
      COMMON/BKSIZR/IMAXPR(1),IMAXBR,KMAXPR(20),KMAXBR(20)   
      COMMON/ILOCGR/ILOCR(600),IWR(210),DSR(200)
      COMMON/IDHIGR/IDMAXR
      COMMON/TOTPTZ/M3Z
      COMMON/DSPACZ/IDSZ
      COMMON/SEGSZ/NSEGZ(1),M2Z,I5Z(95),I2GZ,I2GGZ   
      COMMON/BLKZ/IBLKZ(1),NGBKZ(20),NKFZ(20)    
      COMMON/BCKZ/IDRWZ(100)   
      COMMON/LOCATZ/ILOCPZ(1),ILOCBZ,IRWCPZ(98),IRWCBZ(98),IIWPZ,IIWBZ 
      COMMON/NCONDZ/NCONDZ     
      COMMON/RING3Z/D1Z(98),D2Z(98)    
      COMMON/JUNCTZ/IFIXBZ(588),IFXBZ(588),ITYPEZ(98) 
      COMMON/BKSIZZ/IMAXPZ(1),IMAXBZ,KMAXPZ(20),KMAXBZ(20)   
      COMMON/ILOCGZ/ILOCZ(600),IWZ(210),DSZ(200)
      COMMON/IDHIGZ/IDMAXZ
      COMMON/INTRGX/INTRNG
      COMMON/PRERNG/PNXVAR(736)
      COMMON/ISBSTF/KLAYER(88)
      COMMON/SUBSTX/TSUB(64)
      COMMON/IQSAVX/IQSAVE(6)
      COMMON/CSKINX/CSKIN(36),TSKINX(5),TSKINY(5)
      COMMON/OBJBSX/OBJMIN
      COMMON/IOBJAX/IOBJAL
      COMMON/EIGSLZ/SLPRAT(300),EHILOW(300)
      COMMON/CSORIG/CS0(36)
      COMMON/GRADMZ/GRADMX(30),CONMXJ(30)
      COMMON/ISCAPZ/ISCAPX(30),ICNMAX(30)
      COMMON/IAUTOX/IAUTOC(9)
      COMMON/PHIHTX/PHIHAT,PHITRS
      COMMON/IBPRSX/IBPRES
      COMMON/NEUTRL/DNEUTX,DNEUTY,DSURF
      COMMON/COLBND/FLGCLD,FN1WEB,RCOLD

      REWIND IFILE

      READ(IFILE) AXIAL,CIRC,R
      READ(IFILE) (B0(I),I=1,10)
      READ(IFILE) (B(I),I=1,10)
      READ(IFILE) (ISTIF(I),I=1,14)
      READ(IFILE) (B0SUB(I),I=1,10)
      READ(IFILE) (BSUBX(I),I=1,10)
      READ(IFILE) (ISTFSB(I),I=1,14)
      READ(IFILE) (IMTSUB(I),I=1,8)
      READ(IFILE) (IWIND(I),I=1,8)
      READ(IFILE) RAD2,CURV2
      READ(IFILE) (IFAY(I),I=1,30)
      READ(IFILE) (IPV(I),I=1,162)
      READ(IFILE) (WORDIQ(I),I=1,20)
      READ(IFILE) (CINEQ(I),I=1,400)
      READ(IFILE) (IDINEQ(I),I=1,241)
      READ(IFILE) (ISKIPX(I),I=1,910)
      READ(IFILE) (MAXMAT(I),I=1,11)
      READ(IFILE) (PARMAT(I),I=1,4200)
      READ(IFILE) (WRDMAT(I),I=1,200)
      READ(IFILE) P
      READ(IFILE) (MATL(I),I=1,1080)
      READ(IFILE) (T(I),I=1,180)
      READ(IFILE) (E1(I),I=1,100)
      READ(IFILE) (G13(I),I=1,40)
      READ(IFILE) (GTX(I),I=1,24)
      READ(IFILE) (TX(I), I=1,10)
      READ(IFILE) (STRAIN(I),I=1,800)
      READ(IFILE) (STSMAX(I),I=1,60)
      READ(IFILE) (ALPHA1(I),I=1,60)
      READ(IFILE) (ICOCUR(I),I=1,2)
      READ(IFILE) (TAPE(I),I=1,140)
      READ(IFILE) (DEGRAD(I),I=1,500)
      READ(IFILE) (SIGLUE(I),I=1,20)
      READ(IFILE) (ISOMAT(I),I=1,40)
      READ(IFILE) (VLB(I),I=1,499)
      READ(IFILE) (IADDV(I),I=1,348)
      READ(IFILE) NPAR,NVARB,NALLOW,NCONST,NDEC,NLINK,NESCAP,ITYPE
      READ(IFILE) (PAR(I),I=1,398)
      READ(IFILE) (WORDP(I),I=1,348)
      READ(IFILE) (WORDL(I),I=1,100)
      READ(IFILE) (IDV(I),I=1,450)
      READ(IFILE) (CPWR(I),I=1,300)
      READ(IFILE) CHIALW,PHIMAX
      READ(IFILE) (CX(I),I=1,396)
      READ(IFILE) (FNX(I),I=1,33)
      READ(IFILE) (FNX0(I),I=1,33)
      READ(IFILE) (EIGGEN(I),I=1,5)
      READ(IFILE) (FNVAR(I),I=1,552)
      READ(IFILE) NSEGB5, (IPOINT(I),I=1,295)
      READ(IFILE) NSEGB3, (IPOIN3(I),I=1,295)
      READ(IFILE) M3G
      READ(IFILE) IDSG
      READ(IFILE) (NSEGG(I),I=1,99)
      READ(IFILE) (IBLKG(I),I=1,41)
      READ(IFILE) (IDRWG(I),I=1,100)
      READ(IFILE) (ILOCPG(I),I=1,200)
      READ(IFILE) NCONDG
      READ(IFILE) (D1G(I),I=1,196)
      READ(IFILE) (IFIXBG(I),I=1,1274)
      READ(IFILE) (IMAXPG(I),I=1,42)
      READ(IFILE) (ILOCG(I),I=1,810)
      READ(IFILE) (DSG(I),I=1,200)
      READ(IFILE) IDMAXG
      READ(IFILE) (FBPRE(I),I=1,30)
      READ(IFILE) (MSLOPE(I),I=1,8)
      READ(IFILE) (VARLEG(I),I=1,50)
      READ(IFILE) (MARLEG(I),I=1,100)
      READ(IFILE) IBVAR
      READ(IFILE) (VARPLT(I),I=1,30)
      READ(IFILE) ICURV
      READ(IFILE) (FNXPLT(I),I=1,93)
      READ(IFILE) (FSAFEP(I),I=1,99)
      READ(IFILE) (FSAFP2(I),I=1,99)
      READ(IFILE) (PCWRD1(I),I=1,99)
      READ(IFILE) (PCWRD2(I),I=1,99)
      READ(IFILE) CPLOT1,CPLOT2
      READ(IFILE) (CX0(I),I=1,180)
      READ(IFILE) (NXVAR0(I),I=1,184)
      READ(IFILE) (NYVAR0(I),I=1,184)
      READ(IFILE) (NXYVR0(I),I=1,184)
      READ(IFILE) (NCASEX(I),I=1,5)
      READ(IFILE) ISOGRD,ISOANG
      READ(IFILE) (EFOUND(I),I=1,18)
      READ(IFILE) (ISANDW(I),I=1,16)
      READ(IFILE) (FACSKN(I),I=1,4)
      READ(IFILE) (WOVERL(I),I=1,340)
      READ(IFILE) (ECCORE(I),I=1,24)
      READ(IFILE) (THEX(I),I=1,100)
      READ(IFILE) (ECOREX(I),I=1,60)
      READ(IFILE) (KCORE(I),I=1,36)
      READ(IFILE) (WGTTAB(I),I=1,720)
      READ(IFILE) (SHWTAB(I),I=1,720)
      READ(IFILE) (KOUNTP(I),I=1,60)
      READ(IFILE) (BNDOVR(I),I=1,50)
      READ(IFILE) (ICAND(I),I=1,20)
      READ(IFILE) (CCROSS(I),I=1,200)
      READ(IFILE) (IDINQ1(I),I=1,420)
      READ(IFILE) (IZSTIF(I),I=1,2)
      READ(IFILE) (NSGB52(I),I=1,296)
      READ(IFILE) M3R
      READ(IFILE) IDSR
      READ(IFILE) (NSEGR(I),I=1,99)
      READ(IFILE) (IBLKR(I),I=1,41)
      READ(IFILE) (IDRWR(I),I=1,100)
      READ(IFILE) (ILOCPR(I),I=1,200)
      READ(IFILE) NCONDR
      READ(IFILE) (D1R(I),I=1,196)
      READ(IFILE) (IFIXBR(I),I=1,1274)
      READ(IFILE) (IMAXPR(I),I=1,42)
      READ(IFILE) (ILOCR(I),I=1,810)
      READ(IFILE) (DSR(I),I=1,200)
      READ(IFILE) IDMAXR
      READ(IFILE) M3Z
      READ(IFILE) IDSZ
      READ(IFILE) (NSEGZ(I),I=1,99)
      READ(IFILE) (IBLKZ(I),I=1,41)
      READ(IFILE) (IDRWZ(I),I=1,100)
      READ(IFILE) (ILOCPZ(I),I=1,200)
      READ(IFILE) NCONDZ
      READ(IFILE) (D1Z(I),I=1,196)
      READ(IFILE) (IFIXBZ(I),I=1,1274)
      READ(IFILE) (IMAXPZ(I),I=1,42)
      READ(IFILE) (ILOCZ(I),I=1,810)
      READ(IFILE) (DSZ(I),I=1,200)
      READ(IFILE) IDMAXZ
      READ(IFILE) INTRNG
      READ(IFILE) (PNXVAR(I),I=1,736)
      READ(IFILE) (KLAYER(I),I=1,88)
      READ(IFILE) (TSUB(I),I=1,64)
      READ(IFILE) (IQSAVE(I),I=1,6)
      READ(IFILE) (CSKIN(I),I=1,46)
      READ(IFILE) OBJMIN
      READ(IFILE) IOBJAL
      READ(IFILE) (SLPRAT(I),I=1,300)
      READ(IFILE) (EHILOW(I),I=1,300)
      READ(IFILE) (CS0(I), I=1,36)
      READ(IFILE) (GRADMX(I),I=1,60)
      READ(IFILE) (IAUTOC(I),I=1,9)
      READ(IFILE) PHIHAT,PHITRS
      READ(IFILE) IBPRES
      READ(IFILE) (ISCAPX(I),I=1,60)
      READ(IFILE) DNEUTX,DNEUTY,DSURF
      READ(IFILE) FLGCLD,FN1WEB,RCOLD

      RETURN
      END
