      N         $ Do you want response at resonance to base excitation?
         1      $ NPRT = output options (1=minimum, 2=medium, 3=maximum)
         0      $ ISTRES= output control (0=resultants, 1=sigma, 2=epsilon)
         0      $ NLAST = plot options  (-1=none, 0=geometry, 1=u,v,w)
      N         $ Are there any regions for which you want expanded plots?
         1      $ N0B   = starting number of circ. waves (buckling analysis)
         1      $ NMINB = minimum number of circ. waves  (buckling analysis)
        10      $ NMAXB = maximum number of circ. waves  (buckling analysis)
         1      $ INCRB = increment in number of circ. waves (buckling)
         1      $ NVEC  = number of eigenvalues for each wave number
      Y         $ Do you want to suppress listing the prebuckling resultants?
      Y         $ Do you want to suppress listing the buckling modes?
         0      $ NDIST = number of circ. stations for meridional output
         0      $ NCIRC = number of meridional stations for circ. distibutions
       180      $ THETAS= Nx & Ny along this meridian used in buckling analysis.
