#***********************************************************************
# Makefile parameters for current machine
#***********************************************************************
# special dependencies
# ====================

.SUFFIXES:
.SUFFIXES: .F .f .c .o

# macro definitions for:  X86 Linux using the GNU Fortran compiler (gfortran)
# ===========================================================================

DIR       =  /home/progs/util/test

# DEBUG     =
DEBUG     = -g

CPP       =  /usr/bin/cpp

CPPFLAGS  = -D_linux_

# CLANG     =  ${CC}
CLANG     =  gcc

# CFLAGS    = -O3 -D_linux_
# CFLAGS0   = -O1 -D_linux_

CFLAGS    = -D_linux_
CFLAGS0   = -D_linux_

# FPP       =  /usr/bin/fpp

# FPPFLAGS  = -P

# FORTRAN   =  ${FC}
FORTRAN   =  g77

# FFLAGS    = -O -fno-automatic -fno-globals -Wno-globals -finit-local-zero
# FFLAGSO   = -O -fno-automatic -fno-globals -Wno-globals -finit-local-zero

FFLAGS    = -fno-automatic -fno-globals -Wno-globals -finit-local-zero
FFLAGSO   = -fno-automatic -fno-globals -Wno-globals -finit-local-zero

INCLUDES  = -I.

PPU       =

LINK      = -lm

LIBS      =

AR        =  ar
ARFLAGS   =  rv

CP        =  cp

RM        =  /bin/rm
RMFLAGS   =  -f

# ================================================================
# C-compile rules ( using flags defined above)
# ================================================================

.c.o:
	@echo "==================== compilation of " $*.c "===================="
	${CLANG} ${CFLAGS} ${CPPFLAGS} ${INCLUDES} ${DEBUG} -c $*.c

# ================================================================
# FORTRAN rules  ( using flags defined above)
# ================================================================

.f.o:
	@echo "==================== compilation of " $*.f "===================="
	${FORTRAN} ${FFLAGS} ${PPU} ${DEBUG} -c  $*.f

# ================================================================
# FORTRAN rules  ( using flags defined above)
# ================================================================

.F.o:
	@echo "==================== compilation of " $*.F "===================="
	@echo "==================== compilation of " $*.F "===================="
	/bin/rm -f $*.f
#	${FPP} ${FPPFLAGS} $*.F $*.f
	fpp -P $*.F $*.f
	${FORTRAN} ${FFLAGS}  ${PPU} ${DEBUG} -c  $*.f

# ================================================================
# end of rules
# ================================================================
